# Generated by Django 5.0.6 on 2024-06-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='display',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
